[[snippets]]
prefix = "gd-class"
scope = ["rust"]
body = '''
#[derive(GodotClass)]
#[class(init, base=$2)]
struct $1 {
    base: Base<$2>,
}

#[godot_api]
impl I$2 for $1 {
    fn ready(&mut self) {
		  // called when the node is ready
    }
}
'''
description = "Godot: New Godot class"

[[snippets]]
prefix = "gd-init"
scope = ["rust"]
body = '''
fn init(base: Base<$1>) -> Self {
	// Intantiate the object
	$2
}
'''
description = "Godot: init function"

[[snippets]]
prefix = "gd-ready"
scope = ["rust"]
body = '''
fn ready(&mut self) {
	// called when the node is ready
	$1
}
'''
description = "Godot: ready function"

[[snippets]]
prefix = "gd-process"
scope = ["rust"]
body = '''
fn process(&mut self, delta: f64) {
	// every frame
	$1
}
'''
description = "Godot: process function"

[[snippets]]
prefix = "gd-physics-process"
scope = ["rust"]
body = '''
fn physics_process(&mut self, delta: f64) {
	// every physics frame
	$1
}
'''
description = "Godot: physics-process function"

[[snippets]]
prefix = "gd-enum"
scope = ["rust"]
body = '''
#[derive(GodotConvert, Var, Export, Debug, Default, Clone)]
#[godot(via = GString)]
pub enum $1 {
    #[default]
    $2
}
'''
description = "Godot: New enum"

[[snippets]]
prefix = "bevy-plugin"
scope = ["rust"]
body = '''use bevy::prelude::*;

pub(super) fn plugin(app: &mut App) {
	$1
}'''
description = "Bevy: New top-level function Plugin"

[[snippets]]
prefix = "bevy-component"
scope = ["rust"]
body = '''#[derive(Component, Reflect, Debug)]
#[reflect(Component)]
pub struct $1;'''
description = "Bevy: New Component"

[[snippets]]
prefix = "bevy-bundle"
scope = ["rust"]
body = '''#[derive(Bundle, Reflect, Debug)]
pub struct $1 {
	
}'''
description = "Bevy: New Entity function"

[[snippets]]
prefix = "bevy-resource"
scope = ["rust"]
body = '''#[derive(Resource, Reflect, Debug, Default)]
#[reflect(Resource)]
pub struct $1;'''
description = "Bevy: New Resource"

[[snippets]]
prefix = "bevy-assets"
scope = ["rust"]
body = '''#[derive(Resource, Asset, Clone, Reflect)]
#[reflect(Resource)]
pub struct $1 {
	#[dependency]
	$0
}

impl FromWorld for $1 {
    fn from_world(world: &mut World) -> Self {
        let assets = world.resource::<AssetServer>();

        Self {
				  
        }
    }
}'''
description = "Bevy: New Assets Resource"

[[snippets]]
prefix = "bevy-event"
scope = ["rust"]
body = '''#[derive(Event, Debug)]
pub struct $1;'''
description = "Bevy: New Event"

[[snippets]]
prefix = "bevy-message"
scope = ["rust"]
body = '''#[derive(Message, Debug)]
pub struct $1;'''
description = "Bevy: New Message"

[[snippets]]
prefix = "bevy-systemset"
scope = ["rust"]
body = '''#[derive(SystemSet, Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub enum $1 {
	$0
}'''
description = "Bevy: New SystemSet"

[[snippets]]
prefix = "bevy-schedule"
scope = ["rust"]
body = '''#[derive(ScheduleLabel, Copy, Clone, Eq, PartialEq, Hash, Debug)]
pub struct $1;'''
description = "Bevy: New Schedule"

[[snippets]]
prefix = "bevy-states"
scope = ["rust"]
body = '''#[derive(States, Copy, Clone, Eq, PartialEq, Hash, Debug, Default)]
pub enum $1 {
	#[default]
	$0
}'''
description = "Bevy: New States"

[[snippets]]
prefix = "testmod"
scope = ["rust"]
body = '''#[cfg(test)]
mod tests {
	use super::*;

	#[test]
	fn test_$1() {
		$0
	}
}'''
description = "Rust: Test module with test function"

[[snippets]]
prefix = "test"
scope = ["rust"]
body = '''#[test]
fn test_$1() {
	$0
}'''
description = "Rust: Test function"
