[project]
godot = "4.7.1-stable"
export_templates = true

[sync]
force_overwrite = ["**/*.import", "**/*.uid"]

[[dependency]]
name = "gdscript-formatter"
git = "https://github.com/GDQuest/GDScript-formatter.git"
rev = "0.24.0"

[[dependency]]
name = "gut"
git = "https://github.com/bitwes/Gut.git"
rev = "v9.7.1"

[[dependency]]
name = "godot-statecharts"
git = "https://github.com/derkork/godot-statecharts.git"
rev = "v0.22.5"
exclude = ["godot_state_charts_examples"]

[[dependency]]
name = "godot_doctor"
git = "https://github.com/codevogel/godot_doctor.git"
rev = "2.2.0"

[[dependency]]
name = "yard-godot"
git = "https://github.com/elliotfontaine/yard-godot.git"
rev = "v1.2.0"

[[dependency]]
name = "phantom-camera"
git = "https://github.com/ramokz/phantom-camera.git"
rev = "v0.11.0.3"
